package com.bdqn.dao;

import com.bdqn.pojo.EmpInfo;
import com.bdqn.pojo.EmpInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empinfo
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    int countByExample(EmpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empinfo
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    int deleteByExample(EmpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empinfo
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empinfo
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    int insert(EmpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empinfo
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    int insertSelective(EmpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empinfo
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    List<EmpInfo> selectByExample(EmpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empinfo
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    EmpInfo selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empinfo
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") EmpInfo record, @Param("example") EmpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empinfo
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    int updateByExample(@Param("record") EmpInfo record, @Param("example") EmpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empinfo
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    int updateByPrimaryKeySelective(EmpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empinfo
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    int updateByPrimaryKey(EmpInfo record);
}