package com.bdqn.pojo;

public class EmpInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empinfo.emp_id
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empinfo.emp_name
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empinfo.emp_age
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    private Integer empAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empinfo.emp_address
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    private String empAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empinfo.emp_id
     *
     * @return the value of empinfo.emp_id
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empinfo.emp_id
     *
     * @param empId the value for empinfo.emp_id
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empinfo.emp_name
     *
     * @return the value of empinfo.emp_name
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empinfo.emp_name
     *
     * @param empName the value for empinfo.emp_name
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empinfo.emp_age
     *
     * @return the value of empinfo.emp_age
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    public Integer getEmpAge() {
        return empAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empinfo.emp_age
     *
     * @param empAge the value for empinfo.emp_age
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    public void setEmpAge(Integer empAge) {
        this.empAge = empAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empinfo.emp_address
     *
     * @return the value of empinfo.emp_address
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    public String getEmpAddress() {
        return empAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empinfo.emp_address
     *
     * @param empAddress the value for empinfo.emp_address
     *
     * @mbggenerated Mon Mar 12 10:13:30 CST 2018
     */
    public void setEmpAddress(String empAddress) {
        this.empAddress = empAddress;
    }
}